<a href="https://colab.research.google.com/github/Jorgulas/CIO/blob/main/ex_3_crit_3_altern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Among Us
## Sus
### Sus (smaller)

In [47]:
import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

## Exercicio com 3 critérios e 3 alternativas

# Matriz de comparação dos Critérios
matrix = np.array([[1, 1/2, 4], [2, 1, 7], [1/4, 1/7, 1]])

# Matrizes de comparação de Alternativas
m_c1 = np.array([[1, 1/3, 3], [3, 1, 5], [1/3, 1/5, 1]])

m_c2 = np.array([[1, 5, 1/7], [1/5, 1, 1/8], [7, 8, 1]])

m_c3 = np.array([[1, 2, 1/3], [1/2, 1, 1/4], [3, 4, 1]])


# Definir função de normalizacao
def normalizar_matriz(matriz):
  soma_colunas = np.sum(matriz, axis=0)
  matriz_normalizada = matriz/soma_colunas
  return matriz_normalizada

# calcular VP (vetor das prioridades) (Pesos)
def calcular_vp(matriz):
  return np.mean(matriz, axis=1) # = pesos

# verificar se a matriz é consistente
def calcular_consistencia(matriz, pesos):
  lambda_max = np.mean(np.sum(matriz * pesos, axis=1) / pesos)
  n = matriz.shape[0]
  ci = (lambda_max - n) / (n-1)
  return ci

def calcular_cr(ci, n):
  ri_dict = {1: 0.00, 2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45, 10: 1.49}
  ri = ri_dict.get(n , 1.49) # Se n > 10, usar 1.49 como valor padrão de RI
  cr = ci/ri
  return cr

matrizes_alternativas = [m_c1, m_c2, m_c3]

def ahp(m_criterios, m_altern):
  m_crit_norm = normalizar_matriz(m_criterios)
  print("matriz criterios norm: ", m_crit_norm)
  pesos_crit = calcular_vp(m_crit_norm)
  print("pesos criterios: ", pesos_crit)
  ci_crit = calcular_consistencia(m_criterios, pesos_crit)
  print("ci criterios: ", ci_crit)
  cr_crit = calcular_cr(ci_crit, m_criterios.shape[0])
  print("cr criterios: ", cr_crit)
  if cr_crit > 0.1:
    print(f"A matriz de critérios não é consistente. CR = {cr_crit: .2f}")

  # Calcular pesos das alternativas
  pesos_altern = []
  cr_altern = []
  for i, matriz in enumerate(matrizes_alternativas):
    m_normalizada = normalizar_matriz(matriz)
    print('matriz normalizada: ', m_normalizada)
    pesos = calcular_vp(m_normalizada)
    ci = calcular_consistencia(matriz,pesos)
    cr = calcular_cr(ci, matriz.shape[0])

    if cr > 0.1:
      print(f"Uma das matrizes alternativas (Critério {i+1}) é não consistente. CR = {cr:.2f}")

    pesos_altern.append(pesos)
    cr_altern.append(cr)

  pesos_altern = np.array(pesos_altern).T
  pontuacao_final = np.dot(pesos_altern, pesos_crit)
  return [pesos_crit, cr_crit, pesos_altern, cr_altern, pontuacao_final]

pesos_crit, cr_crit, pesos_altern, cr_altern, pont_final = ahp(matrix, matrizes_alternativas) # matrix -> matriz criterios

print(pesos_crit)
print(cr_crit)
print(pesos_altern)
print(cr_altern)
print(pont_final)

pont_final.sort()
print("Decisão:",pont_final[len(pont_final)-1])


matriz criterios norm:  [[0.30769231 0.30434783 0.33333333]
 [0.61538462 0.60869565 0.58333333]
 [0.07692308 0.08695652 0.08333333]]
pesos criterios:  [0.31512449 0.6024712  0.08240431]
ci criterios:  0.0009910148806386854
cr criterios:  0.001708646345928768
matriz normalizada:  [[0.23076923 0.2173913  0.33333333]
 [0.69230769 0.65217391 0.55555556]
 [0.07692308 0.13043478 0.11111111]]
matriz normalizada:  [[0.12195122 0.35714286 0.11267606]
 [0.02439024 0.07142857 0.09859155]
 [0.85365854 0.57142857 0.78873239]]
Uma das matrizes alternativas (Critério 2) é não consistente. CR = 0.22
matriz normalizada:  [[0.22222222 0.28571429 0.21052632]
 [0.11111111 0.14285714 0.15789474]
 [0.66666667 0.57142857 0.63157895]]
[0.31512449 0.6024712  0.08240431]
0.001708646345928768
[[0.26049796 0.19725671 0.23948761]
 [0.63334572 0.06480345 0.13728766]
 [0.10615632 0.73793983 0.62322473]]
[0.03337472496505753, 0.22498167484776346, 0.015807980379471724]
[0.22066558 0.24993806 0.52939636]
Decisão: 0.529